### ISSUE TITLE
eexec_line in t1disasm can call itself recursively with negative line_len

### ISSUE THREAD

**Issue by nthykier** [kohler/t1utils#9]
Hi,

Jakub Wilk has found a new bug with the afl fuzzer:

```
t1disasm crashes on the attached file:

  $ t1disasm overflow.pfb > /dev/null
  t1disasm: overflow.pfb corrupted: block short by 808463502 bytes at position 1176
  Segmentation fault

GDB says it's integer overflow in line length calculation:

  (gdb) bt
  #0  0xf7e7a7ad in two_way_short_needle (needle_len=13, needle=<optimized out>, haystack_len=4294967295, haystack=0xffffd5fd "/", '0' <repeats 93 times>) at str-two-way.h:312
  #1  __GI___memmem (haystack_start=0xffffd5fd, haystack_len=4294967295, needle_start=<optimized out>, needle_len=13) at memmem.c:72
  #2  0x5655af1b in eexec_line (line=0xffffd5fd "/", '0' <repeats 93 times>, line_len=-1) at t1disasm.c:388
  #3  0x5655b497 in eexec_line (line=0xffffd5d6 "2 index /CharStrings 2 dict dup begin\n /", '0' <repeats 93 times>, line_len=38) at t1disasm.c:396
  #4  0x5655bc5a in disasm_output_binary ( data=0xffffd260 "dup\n/Private 16 dict dup begin\n/RD{string currentfile exch readstring pop}executeonly def\n/ND{noaccess def}executeonly def\n/NP{noaccess put}executeonly def\n/MinFeature{16 16}ND\n/password 5839 def\n/Uni"..., len=926) at t1disasm.c:539
  #5  0x5655a9db in process_pfb (ifp=0x565621c0, ifp_filename=0xffffd947 "overflow.pfb", fr=0xffffd6a0) at t1lib.c:297
  #6  0x56555f76 in main (argc=<optimized out>, argv=<optimized out>) at t1disasm.c:716
  (gdb) up 3
  #3  0x5655b497 in eexec_line (line=0xffffd5d6 "2 index /CharStrings 2 dict dup begin\n /", '0' <repeats 93 times>, line_len=38) at t1disasm.c:396
  396                 return eexec_line((unsigned char *) (CharStrings + 12 + n - 1), line_len - len);
  (gdb) print line_len
  $1 = 38
  (gdb) print len
  $2 = 39
  (gdb) print line_len - len
  $3 = -1

Found using American Fuzzy Lop:
http://lcamtuf.coredump.cx/afl/
```

I have verified that the bug also exists in the 1.39-2 version shipped in Debian, so it is unlikely to have been introduced with the rewrite to memmem in 1.40.

For reference, this is Debian bug 869797 (https://bugs.debian.org/869797).  The file made by Jakub Wilk is available from: https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=869797;filename=overflow.pfb.gz;msg=3

**Comment by kohler** [comment]
I believe I have addressed this problem, and also ran over a bunch of fonts with `-fsanitize` and fixed some UBs. 1.41 released. Thanks!
